"""Application boundary: runtime assembles existing Task, runner and I/O services."""
from typing import Protocol,Any
from ..sprints.ports import SprintWorkPort


class InteractionPort(Protocol):
    def prepare(self,raw:list[dict])->tuple: ...
    def record(self,prepared:tuple,session:str,task:dict|None)->None: ...
    def delivered(self,task:dict|None,report:dict)->None: ...
    def summary(self,task:dict|None)->dict: ...


class WorkResourcesPort(Protocol):
    def factory(self)->Any: ...
    def packet(self,task:dict)->str|None: ...
    def remember(self,task:dict,digest:str)->None: ...


class TaskOverviewPort(Protocol):
    def standalone_summary(self)->list[dict]: ...
    def record(self,task_id:str)->dict|None: ...
    def verification_registry(self,task_id:str)->dict: ...


class WorkRuntime(Protocol):
    accounting: Any
    telemetry: Any
    transfer_tools:Any
    cleanup_tools:Any
    integration_tools:Any
    sprint_tools:SprintWorkPort
    task_queries:TaskOverviewPort
    session:str
    cfg:dict
    interactions:InteractionPort
    work_resources:WorkResourcesPort

    def handoff(self,args:dict)->dict: ...
    def recover_empty_rework(self,task_id:str,reason:str)->dict: ...
    def recover_empty_advance(self,task_id:str,reason:str)->dict: ...
    def recover_missing_worktree(self,task_id:str,reason:str)->dict: ...
    def initialize_stage_contracts(self,**args)->dict: ...
    def revise_stage_contract(self,**args)->dict: ...
    def report_task(self,report:dict)->dict|None: ...
    def show_output(self,receipt_id:str,representation:str,requested:dict|None)->dict: ...
    def current_task(self)->dict|None: ...
    def bootstrap(self,task:dict|None,decision:str|None,feedback:str|None,rework_stage:str|None)->dict: ...
    def verify(self,payload:dict|None)->dict: ...
    def accept(self)->dict: ...
    def cancel(self,reason:str)->dict: ...
    def packet_digest(self,value:object)->str: ...
    def validate_stage_result(self,task_id:str,payload:dict)->None: ...
    def validate_stage_entry(self,task:dict|None=None)->dict: ...
    def validate_stage_scope(self,task:dict|None=None)->dict: ...
    def validate_artifact_paths(self,paths:list[str],task:dict)->list: ...
    def register_artifact_paths(self,paths:list[str],task:dict|None)->list: ...
    def show(self)->dict: ...
    def show_section(self,name:str,stage:str|None,submission:int|None)->dict: ...
    def show_content(self)->dict: ...
    def show_trace(self,route:str,point:str,submission:int|None)->dict: ...
    def show_evidence(self)->dict: ...
    def show_verification_registry(self)->dict: ...
