"""File and registered-artifact observations for acceptance retention."""
from typing import Protocol
from pathlib import Path
from .retention import ArtifactInputs


class AcceptanceRetentionPort(Protocol):
    def observe_manifest_directory(self, task: dict, declaration: ArtifactInputs) -> Path: ...
    def inputs(self, task: dict, declaration: ArtifactInputs) -> list[dict]: ...
    def evidence(self, task: dict, method: dict, receipt: dict) -> list[dict]: ...
    def publish(self, task: dict, declaration: ArtifactInputs, receipt_id: str, value: dict) -> dict: ...
    def read(self, task: dict, reference: dict) -> dict: ...
    def registered(self, task: dict, submitted_paths: list[str]) -> list[dict]: ...
