from __future__ import annotations
from typing import Protocol
from ..sprints.ports import SprintRepository
from .domain import Task, Change


class TaskRepository(Protocol):
    def allocate(self, intent: dict, policy) -> object: ...
    def exists(self, task_id: str) -> bool: ...
    def create(self, task: Task, metadata: dict) -> None: ...
    def load(self, task_id: str) -> Task: ...
    def record_result(self, task_id: str, submission_id: int, report: dict) -> None: ...
    def save(self, change: Change, expected_version: int) -> int | None: ...


class ExecutionRepository(Protocol):
    def create(self, task_id: str, data: dict) -> None: ...
    def load(self, task_id: str) -> tuple[dict, int]: ...
    def patch(self, task_id: str, updates: dict) -> None: ...


class EvidenceRepository(Protocol):
    def record(self, task_id: str, stage: str, iteration: int, receipt: dict) -> None: ...
    def list_for(self, task_id: str) -> list[dict]: ...


class TaskUnitOfWork(Protocol):
    handoffs: "HandoffRepository"
    sprints: "SprintRepository"
    tasks: TaskRepository
    execution: ExecutionRepository
    evidence: EvidenceRepository
    def __enter__(self) -> TaskUnitOfWork: ...
    def __exit__(self, exc_type, exc, traceback) -> bool: ...


class HandoffRepository(Protocol):
    def get(self,actor:str,request_id:str)->dict|None: ...
    def latest(self,task_id:str)->dict|None: ...
    def insert(self,record:dict)->None: ...
    def replace(self,record:dict)->None: ...
    def unbind(self,actor:str,task_id:str)->None: ...
    def bind(self,actor:str,task_id:str)->None: ...
