from __future__ import annotations
from typing import Protocol
from ..sprints.ports import SprintRepository
from .domain import Task, TaskState, Change, EmptyReworkRecoveryPoint


class TaskRepository(Protocol):
    def action_receipt(self, task_id: str, request_id: str, digest: str) -> dict | None: ...
    def allocate(self, intent: dict, policy, reserved_ids=()) -> object: ...
    def create_newborn(self, newborn: object, config_hash: str) -> None: ...
    def detach_newborn(self, task_id: str, expected_sprint: str) -> None: ...
    def exists(self, task_id: str) -> bool: ...
    def create(self, task: Task, metadata: dict) -> None: ...
    def load(self, task_id: str) -> Task: ...
    def load_newborn(self, task_id: str) -> object: ...
    def is_newborn(self, task_id: str) -> bool: ...
    def acquire_newborn(self, task_id: str, actor: str) -> None: ...
    def release_newborn(self, task_id: str, actor: str) -> None: ...
    def membership_snapshot(self, task_id: str) -> dict: ...
    def change_sprint_membership(
        self, task_id: str, expected_sprint: str | None,
        target_sprint: str | None, expected_version: int,
    ) -> None: ...
    def restart_context(self, task_id: str) -> dict: ...
    def publish_requirements_context(
        self, task_id: str, snapshot: dict, agreement: dict
    ) -> None: ...
    def restart_newborn(
        self, newborn: object, expected_version: int, config_hash: str,
        reason: str, authorization: str,
    ) -> None: ...
    def remember_action(self, task_id: str, actor: str, request_id: str,
                        digest: str, result: dict) -> None: ...
    def begin_progression(
        self, task_id: str, actor: str, request_id: str, digest: str,
        target_stage: str,
    ) -> dict: ...
    def finish_progression(
        self, task_id: str, actor: str, request_id: str, stage_id: str
    ) -> None: ...
    def empty_rework_recovery_point(
        self, task_id: str, handoff_version: int, last_report: dict,
        transition_event: str = "user_rework",
    ) -> EmptyReworkRecoveryPoint: ...
    def ownership_event_suffix(
        self, task_id: str, after_version: int, through_version: int
    ) -> tuple[str, ...]: ...
    def cancellation_recovery_point(self, task_id: str, version: int) -> TaskState: ...
    def review_identity(self, task_id: str) -> dict | None: ...
    def record_result(self, task_id: str, submission_id: int, report: dict, *, actor: str) -> None: ...
    def save(self, change: Change, expected_version: int) -> int | None: ...
    def stage_contract_receipt(self, task_id: str, request_id: str, intent: dict) -> dict | None: ...
    def save_stage_contract_change(
        self, change: Change, expected_version: int, audit: dict
    ) -> dict: ...
    def stage_contract_context(self, task_id: str) -> dict: ...


class RepositoryTreeReader(Protocol):
    def existing_paths(self, revision: str, paths: tuple[str, ...]) -> frozenset[str]: ...


class ExecutionRepository(Protocol):
    def save(self, task_id: str, data: dict, expected_version: int) -> int: ...
    def create(self, task_id: str, data: dict) -> None: ...
    def exists(self, task_id: str) -> bool: ...
    def load(self, task_id: str) -> tuple[dict, int]: ...
    def patch(self, task_id: str, updates: dict) -> None: ...
    def restart(self, task_id: str) -> None: ...


class EvidenceRepository(Protocol):
    def record(self, task_id: str, stage: str, iteration: int, receipt: dict) -> None: ...
    def list_for(self, task_id: str) -> list[dict]: ...
    def timeout_history(self, profile: dict) -> dict: ...


class WorkPacketRepository(Protocol):
    def current(self, task_id: str, stage: str, iteration: int) -> str | None: ...
    def remember(
        self, task_id: str, stage: str, iteration: int, digest: str,
    ) -> None: ...
    def invalidate(self, task_id: str) -> None: ...


class ArtifactLinkRepository(Protocol):
    def link_task(self, task_id: str, artifacts: list[dict]) -> None: ...


class TaskUnitOfWork(Protocol):
    handoffs: "HandoffRepository"
    sprints: "SprintRepository"
    tasks: TaskRepository
    execution: ExecutionRepository
    evidence: EvidenceRepository
    ownership: object
    work_packets: WorkPacketRepository
    artifacts: ArtifactLinkRepository
    def __enter__(self) -> TaskUnitOfWork: ...
    def __exit__(self, exc_type, exc, traceback) -> bool: ...


class HandoffRepository(Protocol):
    def get(self,actor:str,request_id:str)->dict|None: ...
    def latest(self,task_id:str)->dict|None: ...
    def latest_recovery_candidate(self,task_id:str)->dict|None: ...
    def insert(self,record:dict)->None: ...
    def replace(self,record:dict)->None: ...
    def unbind(self,actor:str,task_id:str)->None: ...
    def bind(self,actor:str,task_id:str)->None: ...


class TaskProcessMigrationPort(Protocol):
    def migrate(self, request: object) -> dict: ...
