from typing import Protocol


class SprintRepository(Protocol):
    def get(self, sprint_id: str) -> dict | None: ...
    def save(self, record: dict, expected_revision: int | None) -> None: ...
    def publish_members(self, record: dict) -> None: ...
    def add_draft_member(self, sprint_id: str, task_id: str) -> None: ...
    def remove_draft_member(self, sprint_id: str, task_id: str) -> None: ...
    def receipt(self, sprint_id: str, request_id: str, digest: str) -> dict | None: ...
    def remember(self, sprint_id: str, request_id: str, digest: str, result: dict) -> None: ...
    def bind(self, session: str, sprint_id: str) -> None: ...
    def scope(self, session: str) -> str | None: ...
    def facts(self, sprint_id: str) -> dict: ...
    def published_ids(self, project: str) -> list[str]: ...


class SprintWorkPort(Protocol):
    def apply(self, packet: dict) -> dict: ...
    def overview(self, sprint_id: str | None) -> dict | None: ...
    def known(self, sprint_id: str) -> bool: ...
    def select(self, sprint_id: str) -> dict: ...
    def start(self, task_id: str) -> dict: ...
    def query(self, sprint_id: str | None, view: str) -> dict: ...
    def overviews(self) -> list[dict]: ...
