"""Action storage lives behind short transactions, outside external effects."""
from typing import Protocol
from .domain import ActionRun

class ActionRepository(Protocol):
    def load(self,task_id:str,stage:str,iteration:int)->dict|None: ...
    def create(self,task_id:str,stage:str,iteration:int,value:dict)->None: ...
    def save(self,task_id:str,stage:str,iteration:int,value:dict,expected_version:int)->None: ...

class ActionUnitOfWork(Protocol):
    actions:ActionRepository
    tasks:object
    def __enter__(self): ...
    def __exit__(self,exc_type,exc,traceback): ...
