from pathlib import Path
import json
import os
import subprocess
import sys
import pytest


@pytest.mark.parametrize('scenario,commands,args,decisions',[
    ('command_negative',1,0,0),('logical',0,1,1),('mixed',1,1,1),('observe_feedback',2,2,2)])
def test_documented_evidence_cli_routes(tmp_path,scenario,commands,args,decisions):
    root=Path(__file__).resolve().parents[2]
    out=tmp_path/'evidence-demo'
    result=subprocess.run([sys.executable,str(root/'examples/evidence_demo.py'),'--directory',str(out),'--scenario',scenario],
                          env={**{k:v for k,v in os.environ.items() if k != 'LANG'},
                               'PYTHONPATH':str(root/'src'),
                               'POISE_CALLER_BINDING':str(tmp_path/'outer-caller.json'),
                               'CODEX_SESSION_ID':'outer-demo-test-session',
                               'CODEX_THREAD_ID':'outer-demo-test-thread'},capture_output=True,text=True,timeout=40)
    assert result.returncode==0,result.stdout+result.stderr
    data=json.loads((out/'evidence-report.json').read_text())
    assert data['status']=='PASS' and data['task_status']=='completed'
    assert (data['command_executions'],data['arguments'],data['decisions'])==(commands,args,decisions)
    assert data['raw_output_survives_cleanup'] is True
    if scenario=='command_negative': assert data['stage_outcomes'][0]=='not_satisfied'

    # The disposable demo must establish its own supported identity, not reuse
    # or overwrite the invoking agent's native or persisted caller.
    assert not (tmp_path/'outer-caller.json').exists()
    home=out/'poise'
    caller=json.loads((home/'caller.json').read_text())
    assert caller['schema']=='poise-caller-binding-1' and caller['caller_id']
    task=json.loads((home/'task.json').read_text())
    snapshot=task['requirements_snapshot']
    assert [x['text'] for x in snapshot['task_requirements']]==task['requirements']
    assert [x['task_text'] for x in task['requirements_agreement']['chains']]==task['requirements']
    assert task['requirements_agreement']['accepted'] is True
    assert {x['stage_id'] for x in task['stage_contracts']}=={'measure','audit'}
    assert {x['stage'] for x in task['decomposition']['phases']}=={'measure','audit'}
    assert all(not x['allowed_paths'] for x in task['stage_contracts'])
    assert snapshot['task_requirements'][0]['applications']==['DEMO-EVIDENCE']
    assert snapshot['requirements']['DEMO-EVIDENCE']['level']=='application'
    assert snapshot['links']==[{'system':'DEMO-SYS','application':'DEMO-EVIDENCE'}]

    # All roles below are synthetic scenario participants, not independent
    # engineering reviewers. Each gets a binding generated by public Poise.
    reviewer=json.loads((home/'reviewer-caller.json').read_text())
    assert reviewer['schema']=='poise-caller-binding-1'
    assert reviewer['caller_id'] != caller['caller_id']
    handoffs=[call for call in data['calls'] if call['operation']=='handoff']
    assert len(handoffs)==(3 if scenario=='observe_feedback' else 1)
    assert all(call['status']=='handed_off' for call in handoffs)
    config=json.loads((home/'project.json').read_text())
    assert 'LANG' in config['environment_names']
