"""Ports for durable delivery authority and bounded material effects."""
from typing import Protocol, ContextManager
from .domain import DeliveryState


class DeliveryRepository(Protocol):
    def read(self, task_id: str) -> DeliveryState | None: ...
    def agreement_request(self, task_id: str, request_id: str, intent_digest: str) -> dict | None: ...
    def save(self, actor: str, state: DeliveryState, expected_revision: int) -> None: ...


class DeliveryEffects(Protocol):
    def locked(self) -> ContextManager: ...
    def admission(self, task_id: str, actor: str) -> dict: ...
    def prepare(self, record: dict, agreement: dict) -> tuple: ...
    def ensure_resources(self, record: dict, state: DeliveryState) -> None: ...
    def retiring_artifacts(self, state: DeliveryState) -> list[str]: ...
    def preparing_consumer(self, task_id: str) -> bool: ...
    def consumer_blocker(self, record: dict) -> str | None: ...
    def blocker(self, record: dict, state: DeliveryState) -> str | None: ...
    def validate_sources(self, state: DeliveryState) -> str | None: ...
    def confirm_output(self, output: dict) -> tuple: ...
    def remove_owned_root(self, state: DeliveryState) -> None: ...
