from typing import Protocol

class CatalogueRepository(Protocol):
    def process_selection(self,goal_type:str)->dict: ...
    def task_blueprint(self,selection:dict): ...
    def process_template(self,selection:dict)->dict: ...
    def configured_process(self,goal_type:str)->dict: ...
