from typing import Protocol
from .clock import ClockObservation

class AccountingPort(Protocol):
    def prepare(self,value:dict)->dict: ...
    def receive(self,prepared:dict,task:dict|None)->None: ...
    def begin(self,operation:str,task:dict|None,prepared:dict|None,turn_id:str|None)->None: ...
    def finish(self,operation:str,before:dict|None,after:dict|None,result:dict)->None: ...
    def close_cycle(self)->None: ...
    def report(self,query:dict)->dict: ...

class AccountingRepository(Protocol):
    def ingest(self,prepared:dict,session:str,task:dict|None)->None: ...
    def start(self,session:str,task:dict,at:ClockObservation,turn_id:str|None)->None: ...
    def new_turn(self,session:str,turn_id:str|None)->None: ...
    def touch(self,session:str,at:ClockObservation)->None: ...
    def stop(self,session:str,at:ClockObservation)->None: ...
    def baseline(self,task_id:str)->dict|None: ...
