from typing import Protocol
from .clock import ClockObservation

class AccountingPort(Protocol):
    def process(self,envelope)->None: ...
    def report(self,query:dict)->dict: ...
    def telemetry_summary(self,runtime:dict)->dict: ...

class AccountingRepository(Protocol):
    def release_cycle(self,session:str,task_id:str)->None: ...
    def ingest_binding(self,prepared:dict,session:str,binding:dict)->None: ...
    def store_telemetry(self,envelope)->bool: ...
    def start(self,session:str,task:dict,at:ClockObservation,turn_id:str|None)->None: ...
    def new_turn(self,session:str,turn_id:str|None)->None: ...
    def touch(self,session:str,at:ClockObservation)->None: ...
    def stop(self,session:str,at:ClockObservation)->None: ...
    def baseline(self,task_id:str)->dict|None: ...
